Add test slack back
tiiuae/ghaf-jenkins-pipeline pull request #106
Opened 2024-12-03 10:28 UTC by mnokka-unikie

Adding back slacking of main build HW test failures

2024-12-04 13:37 UTC, joinemm requested changes

2024-12-04 13:37 UTC, joinemm commented on utils.groovy
> +            failedTargets.add(target)
should use `targetAttr` here as the targets can have same name but different system.

2024-12-04 13:37 UTC, joinemm commented on utils.groovy
> +    def target = "${it.target}"
unnecessary

2024-12-04 13:37 UTC, joinemm commented on utils.groovy
> +    return (flakeref)
parenthesis intentional?

2024-12-08 14:35 UTC, mnokka-unikie commented on utils.groovy
> +            failedTargets.add(target)
changed using targetAttr, force committed PR

2024-12-08 14:35 UTC, mnokka-unikie commented on utils.groovy
> +    return (flakeref)
cleaned off

2024-12-08 14:35 UTC, mnokka-unikie commented on utils.groovy
> +    def target = "${it.target}"
not used anymore

2024-12-09 09:24 UTC, joinemm approved these changes

2024-12-10 09:25 UTC, henrirosten commented
@mnokka-unikie: Can we close this?

2025-01-08 13:03 UTC, joinemm commented
changes already merged in another PR, closing

2025-01-08 13:03 UTC, closed without merging