HW test failure slacking
tiiuae/ghaf-jenkins-pipeline pull request #112
Opened 2024-12-10 07:16 UTC by mnokka-unikie

Reintroduced hw test errors slacking and merging to latest main as a new fresh branch

2024-12-10 08:05 UTC, cazfi requested changes

2024-12-10 08:05 UTC, cazfi commented on utils.groovy
> +    return flakeref
This says it's a flake reference...

2024-12-10 08:05 UTC, cazfi commented on utils.groovy
> +            errorstatus=ghaf_hw_test(targetAttr, it.hwtest_device, '_boot_bat_perf_')
...this says it's an error status...

2024-12-10 08:05 UTC, cazfi commented on utils.groovy
> +              println ("ERROR FOUND, target: ${errorstatus}")
...and these claim it to be a target.

Rework variable naming etc to make it clear what it is.

2024-12-12 09:29 UTC, mnokka-unikie commented on utils.groovy
> +              println ("ERROR FOUND, target: ${errorstatus}")
using same naming now, forced pushed change

2024-12-12 09:29 UTC, mnokka-unikie commented
force pushed change, using same var naming now

2024-12-16 11:55 UTC, cazfi commented on utils.groovy
> +            if (errorstatus==null) {
Should this be flakeref?

2024-12-16 11:55 UTC, cazfi commented on utils.groovy
> +              failedHWTests.add(errorstatus)
Should this be flakeref?

2024-12-16 12:45 UTC, mnokka-unikie commented on utils.groovy
> +            if (errorstatus==null) {
indeed, fixed directly

2024-12-16 12:45 UTC, mnokka-unikie commented on utils.groovy
> +              failedHWTests.add(errorstatus)
indeed, fixed directly

2024-12-16 12:47 UTC, cazfi approved these changes

2024-12-23 08:45 UTC, merged