Implement Format Checks for Groovy Code in GitHub Actions Workflow
tiiuae/ghaf-jenkins-pipeline pull request #16
Opened 2024-05-08 12:36 UTC by karim20230

In this change, I have implemented a new GitHub Actions workflow named "Format-checks". This workflow is triggered on every push and pull request to the 'main' branch.

This change will help to ensure that all Groovy code in the repository adheres to our coding standards and best practices, and will prevent code with formatting errors from being merged into the 'main' branch.

--failon error  -The command will cause the workflow to fail if any errors are detected by GroovyLint.

2024-05-09 23:24 UTC, cazfi submitted a review, later dismissed

2024-05-09 23:24 UTC, cazfi commented on .github/workflows/format-checks.yml
> +    runs-on: ubuntu-latest
Pin to specific version (22.04), and not to unexpectedly changing "...-latest"

2024-05-10 08:26 UTC, mkaapu commented
Jenkins Declarative Pipeline is not exactly groovy, but simple text scripts that use a Pipeline DSL (domain-specific language) based on the Groovy programming language.
There are better option for linting Pipeline scripts and Jenkins installation itself comes with linter tool:
https://www.jenkins.io/doc/book/pipeline/development/

2024-05-22 15:35 UTC, karim20230 commented
> Jenkins Declarative Pipeline is not exactly groovy, but simple text scripts that use a Pipeline DSL (domain-specific language) based on the Groovy programming language. There are better option for linting Pipeline scripts and Jenkins installation itself comes with linter tool: https://www.jenkins.io/doc/book/pipeline/development/

Yeah agreed! also  `npm-groovy-lint` tool is also designed to lint Groovy code,  issues in a Jenkins Pipeline script. the tool can check Groovy code for example style issues, potential bugs, and other problems. for example  Runing `npm-groovy-lint` with the `--fix` option on all files in the directory. The `--fix` option automatically fixes any fixable issues in the code.

2024-05-22 15:43 UTC, karim20230 commented on .github/workflows/format-checks.yml
> +    runs-on: ubuntu-latest
specified version 22.04

2024-05-23 10:15 UTC, henrirosten requested changes

2024-05-23 10:15 UTC, henrirosten commented on README.md
> + It automatically checks the formatting of the Groovy code whenever a push is made to our ghaf-jenkins-pipeline `main` branch or a pull request is opened against it.
Please remove this from the main README.md, instead, if you feel such documentation needs to be provided, I would propose adding the relevant parts directly to the `format-checks.yml` as comments.

2024-05-23 10:15 UTC, henrirosten commented on .github/workflows/format-checks.yml
> +          node-version: 16
Why not use the latest node version?

2024-05-23 10:15 UTC, henrirosten commented on .github/workflows/format-checks.yml
> +        run: npm-groovy-lint --fix . || true
Please don't run the `--fix` in the github action. The point of this check is to fail if the code fails to comply, right?

Now, doesn't this line (#26) silently fix any errors locally, so the `--failon error` on line #28 would never fail?

2024-05-23 10:15 UTC, henrirosten commented on .github/workflows/format-checks.yml
> +        run: npm-groovy-lint --failon error . || true
Why do you ignore possible linting errors with `|| true`? Now, this check would always pass, no?

The point of this check is to fail if the code fails to comply, right?

2024-05-23 10:15 UTC, henrirosten commented on .github/workflows/format-checks.yml
> +        run: npm-groovy-lint --fix . || true
Suggestion: remove lines 25 and 26

2024-05-23 10:15 UTC, henrirosten commented on .github/workflows/format-checks.yml
> +        run: npm-groovy-lint --failon error . || true
Suggestion: remove `|| true`.
It will fail initially, but you need to fix the linting errors as part of this PR.

2024-05-23 10:44 UTC, karim20230 commented on .github/workflows/format-checks.yml
> +        run: npm-groovy-lint --fix . || true
Sure btw  this way, the `npm-groovy-lint` command will only report issues, not fix them, and the `--failon error` command will cause the workflow to fail if there are any errors.

2024-05-23 10:45 UTC, karim20230 commented on README.md
> + It automatically checks the formatting of the Groovy code whenever a push is made to our ghaf-jenkins-pipeline `main` branch or a pull request is opened against it.
Sure

2024-05-23 10:48 UTC, karim20230 commented on .github/workflows/format-checks.yml
> +          node-version: 16
Well  v16 is used because it's the current LTS version and it's  stable, will be maintained for a long time!

2024-05-23 11:07 UTC, karim20230 commented on .github/workflows/format-checks.yml
> +        run: npm-groovy-lint --failon error . || true
sure

2024-05-23 11:16 UTC, henrirosten commented on .github/workflows/format-checks.yml
> +        run: npm-groovy-lint --fix . || true
Yes, that's what we want

2024-05-23 11:19 UTC, henrirosten commented on .github/workflows/format-checks.yml
> +          node-version: 16
Please re-check. Isn't version 20 the current LTS?
Also noticed the setup-node@v3 is an old version too, please use the latest action version also.

2024-05-23 11:24 UTC, karim20230 commented on .github/workflows/format-checks.yml
> +          node-version: 16
Nope seems  22

2024-05-23 11:39 UTC, karim20230 commented on .github/workflows/format-checks.yml
> +          node-version: 16
and well I think we  need kept actions/setup-node@v3 as it's the latest version available at the time (May 23, 2024).

2024-05-23 11:48 UTC, henrirosten commented on .github/workflows/format-checks.yml
> +          node-version: 16
No, I think v4 is the latest based on: https://github.com/actions/setup-node/releases

2024-05-23 11:58 UTC, karim20230 commented on .github/workflows/format-checks.yml
> +          node-version: 16
yeah I see thanks btw  for example if we are going to use v20.13.1 should be absolutely fine to use setup-node@v3

2024-05-23 13:28 UTC, karim20230 commented
Although there are warnings and informational messages, there are zero errors reported.

I believe that means the code compiles and functions as intended. btw though checks fails we maybe need to improve code style!

2024-05-24 08:01 UTC, henrirosten commented on .github/workflows/format-checks.yml
> +        run: npm-groovy-lint --failon error .
Please remove lines 29 and 30.

I would suggest to only with the `--failon error` check.
If you also want the check to fail on other error levels (warning, info) too please state it explicitly e.g. with `--failon warning`.

In any case, you need to fix the current pipeline scripts, so they comply with the check you are adding here.

2024-05-24 08:11 UTC, karim20230 commented on .github/workflows/format-checks.yml
> +        run: npm-groovy-lint --failon error .
gone and workflow will only fail if there are really errors in the Groovy code

2024-05-24 08:15 UTC, henrirosten approved these changes

2024-05-24 08:21 UTC, merged