Add slacking for failed builds
tiiuae/ghaf-jenkins-pipeline pull request #33
Opened 2024-06-24 13:35 UTC by mnokka-unikie

Slacks failed builds to defined channels. Currently dev and priv Jenkins have dedicated Slack channels defined for usage.

2024-06-25 08:20 UTC, mkaapu requested changes

2024-06-25 08:20 UTC, mkaapu commented on ghaf-main-pipeline.groovy
> +                    if (env.SERVER_NAME == "") {
Fix indentation

2024-06-25 08:49 UTC, henrirosten commented on ghaf-main-pipeline.groovy
> +                    if (env.SERVER_NAME == "") {
Note: Not only here, but throughout the changes you have made.

2024-06-25 09:11 UTC, henrirosten commented on utils.groovy
> +}
There are several problems with this function, most importantly, I don't think we can draw a conclusion that if the server name contains 'dev' or 'prod', that we could generally determine that it's then 'dev' or 'prod' instance.

I would propose the following:
- Completely remove this function
- Start with adding 'slacking' to one pipeline, perhaps to the `ghaf-main-pipeline.groovy`
- In the post step of the given pipeline, determine if 'slacking' is needed based on the hostname (as returned by `uname -n`). Only proceed with 'slacking' if hostname matches `ghaf-jenkins-controller-dev`

2024-06-28 10:01 UTC, mnokka-unikie commented
closing, changes implemented top of current main in a new PR

2024-06-28 10:01 UTC, closed without merging

2024-06-28 10:26 UTC, henrirosten commented
@mnokka-unikie : generally, you don't need to introduce a new PR to have it rebased on the new main. Simply rebase locally, then force-push to your branch and it will update the PR too.