Add FMO-OS main pipeline
tiiuae/ghaf-jenkins-pipeline pull request #37
Opened 2024-07-08 13:56 UTC by mkaapu

Add FMO-OS main pipeline

This implementation is combining scripted parallel steps and use of utils module.

2024-07-08 20:18 UTC, cazfi requested changes

2024-07-08 20:18 UTC, cazfi commented on fmo-os-main-pipeline.groovy
> +    FMO_REF = params.getOrDefault('BRACH', DEFAULT_REF)
Should this be 'BRANCH'?

2024-07-09 07:53 UTC, mkaapu commented on fmo-os-main-pipeline.groovy
> +    FMO_REF = params.getOrDefault('BRACH', DEFAULT_REF)
> Should this be 'BRANCH'?

Even the checkout scmGit argument is named branches, its value can be a branch, a tag, or even a commit hash.
So, pretty much any git reference will do as value.

For instance, when testing the project logic in Jenkins, I usually use the same git commit which was used as a base for previous build as a value for the project parameter, to achieve faster nix builds.

2024-07-09 07:59 UTC, cazfi commented on fmo-os-main-pipeline.groovy
> +    FMO_REF = params.getOrDefault('BRACH', DEFAULT_REF)
I mean there's a typo, missing "N" in "BRACH"

2024-07-10 05:51 UTC, cazfi approved these changes

2024-07-11 14:06 UTC, merged