Add sbomnix to current Jenkins pipeline
tiiuae/ghaf-jenkins-pipeline pull request #5
Opened 2024-04-12 12:07 UTC by mnokka-unikie

2024-04-12 12:28 UTC, henrirosten reviewed
In addition to the below comment
- please check the script format (preferably with a tool of somesort). As it now is, the indentation and formatting is a mess.
- please squash any commits that don't need to be kept in the history.
- please provide a short description as to what and why was changed.

2024-04-12 12:28 UTC, henrirosten commented on ghaf-build-pipeline.groovy
> +                        echo "The sbomnix command succeeded. Carry on as normally"
Why not have the sbomnix invocations as a separate step after the build steps?
I would prefer keeping the pipeline script as simple as possible, even at the expense of few more keystrokes.

Also, I believe we will not want to run sbomnix (let alone some other tools we'll later add to this pipeline) against all targets we'll run the build targets for.

2024-04-16 12:48 UTC, mkaapu commented
No need to merge this to main.
I could scrap ideas from this PR and add them to refactoring work which is still under work.

SBOM generation has been also tested here:
https://github.com/tiiuae/ghaf-jenkins-pipeline/blob/WIP-PoC-matrix/Jenkinsfile
Jenkinsfile from the WIP-PoC branch will be taken into use in our ghaf-infra dev environment.

2024-04-16 12:50 UTC, mkaapu requested changes

2024-04-16 12:50 UTC, mkaapu commented on ghaf-build-pipeline.groovy
> +               def builds= [
You can implement this with matrix or parallel stages of declarative pipeline:
https://www.jenkins.io/doc/book/pipeline/syntax/#parallel
If we can keep Jenkinsfiles simple with as less custom scripting as possible, they stay more readable and will be easier to maintain.

2024-04-19 10:29 UTC, mnokka-unikie commented on ghaf-build-pipeline.groovy
> +               def builds= [
Simplified with parallel stages for builds and sbomnix usage. Used parallel operations to speed artifacts creations

2024-04-19 10:45 UTC, mkaapu requested changes

2024-04-19 11:02 UTC, henrirosten commented on ghaf-build-pipeline.groovy
> +            def artifactsToArchive = sh(script: "find ${directoryPath} -type f -name 'result-*'", returnStdout: true).trim().split('\n')
The artifacts archive will soon change with https://ssrc.atlassian.net/browse/SP-4255, so I would not spend too much time improving the 'old' way of archiving artifacts. I would be fine with dropping this part completely from the PR.

2024-04-19 11:05 UTC, henrirosten commented on ghaf-build-pipeline.groovy
>        }
Are you using indentation of 3 spaces here? Please keep the original indentation instead.

2024-04-19 11:08 UTC, henrirosten commented on ghaf-build-pipeline.groovy
> +        }
Same thing here, please fix the indentation

2024-04-19 16:34 UTC, mnokka-unikie commented on ghaf-build-pipeline.groovy
> +            def artifactsToArchive = sh(script: "find ${directoryPath} -type f -name 'result-*'", returnStdout: true).trim().split('\n')
returned old way with added verbal operation whats being created

2024-04-19 16:35 UTC, mnokka-unikie commented on ghaf-build-pipeline.groovy
>        }
gone and checked 2 space steps

2024-04-19 16:35 UTC, mnokka-unikie commented on ghaf-build-pipeline.groovy
> +        }
gone and checked 2 space steps

2024-06-07 12:42 UTC, closed without merging