Build pre-merge pipeline targets in parallel
tiiuae/ghaf-jenkins-pipeline pull request #70
Opened 2024-09-17 14:01 UTC by joinemm

Use `nix-eval-jobs` to parallel build targets in pre-merge pipeline.

2024-09-17 20:14 UTC, cazfi requested changes

2024-09-17 20:14 UTC, cazfi commented on ghaf-pre-merge-pipeline.groovy
> +// Must match target names defined in #hydraJobs
Please don't refer to "hydrajobs" here. It's likely going completely away along the legacy CI/CD.

2024-09-17 20:14 UTC, cazfi commented on ghaf-pre-merge-pipeline.groovy
> +            def flakeAttr = ".#hydraJobs"
Ok to have it like this in this PR (since we can't have it another way yet), but agree with ghaf developers what should the attribute name be in the future.

2024-09-18 05:24 UTC, joinemm commented
Required before merging: https://github.com/tiiuae/ghaf-infra/pull/249

2024-09-18 05:29 UTC, joinemm commented on ghaf-pre-merge-pipeline.groovy
> +            def flakeAttr = ".#hydraJobs"
Yeah it doesn't have to be hydrajobs in the future but for now that is the easiest way to get all targets. If we were to evaluate `.#packages`, it would take very long time as there are a lot of outputs we don't care about under that name, in addition to the build targets.

2024-09-18 05:29 UTC, cazfi approved these changes

2024-09-18 05:34 UTC, henrirosten commented
Would this also require increasing the number of executors on the Jenkins config?

In my opinion, this change makes the "Stage View" unreadable. Also, I thinks it becomes harder to read the logs to see what was the failure cause on a build failure.

However, such usability concerns might be more of a personal preference, and potential build time improvements this change introduces are far more important.

I think we should definitely give it a try.

2024-09-18 05:36 UTC, joinemm commented
It's not necessary to increase the amount of executors. As for the readability, I would suggest using the blue ocean view when possible

2024-09-18 05:51 UTC, henrirosten commented
_>  As for the readability, I would suggest using the blue ocean view when possible_

Not a matter of this PR, but we could later think of changing the github PR status link (which is set in the post step) so it would point to the relevant blue ocean view.

2024-09-18 05:56 UTC, joinemm commented
Yes I think that's a good idea

2024-09-18 06:03 UTC, henrirosten approved these changes

2024-09-18 12:22 UTC, merged