Add ghaf-parallel-pipelines
tiiuae/ghaf-jenkins-pipeline pull request #75
Opened 2024-10-10 12:36 UTC by vjuntunen

Add ghaf-prallel-pipeline to test
hw tests parallel with parallel builds

Add ghaf-parallel-hw-test pipeline
to run target tests on dedicated agent-service
for each target device

Add own parallel hw test function to utils.groovy

2024-10-10 12:52 UTC, cazfi commented on ghaf-hw-test.groovy
> +          sh "nix run github:tiiuae/ci-yubi/bdb2dbf#verify -- --path ${img_relpath} --sigfile ${sig_relpath}"
Maybe have the hash part in a variable defined on top, to make updating it more obvious.

2024-10-10 12:52 UTC, cazfi commented on utils.groovy
> +  currentBuild.description = "<a href=\"${href}\">📦 Artifacts</a>"
What if the description has been set already, to contain something else than artifacts link? The removed code had functionality to just add the artifacts link.

2024-10-10 12:53 UTC, henrirosten commented on ghaf-hw-test.groovy
> +          sh "nix run github:tiiuae/ci-yubi/bdb2dbf#verify -- --path ${img_relpath} --sigfile ${sig_relpath}"
This was added already in https://github.com/tiiuae/ghaf-jenkins-pipeline/commit/f383f57335f1ac61a8b99571377e1bf04cefdacf.

Please rebase and only include your changes to this PR, otherwise it's impossible to review.

2024-10-11 06:54 UTC, vjuntunen commented on utils.groovy
> +  currentBuild.description = "<a href=\"${href}\">📦 Artifacts</a>"
I think there is some fix for this and this is not something that I've added in first place.

2024-10-11 07:34 UTC, joinemm requested changes

2024-10-11 07:34 UTC, joinemm commented on ghaf-parallel-pipeline.groovy
> +                      if (it['archive']) {
`it['archive']` doesn't exist. archival should be toggled with hwtest_device not being null

2024-10-11 07:34 UTC, joinemm commented on ghaf-parallel-pipeline.groovy
> +                    if(it['hwtest_device'] != null) {
archive step should be inside this if block so we don't try to archive targets with no out-links

2024-10-11 07:34 UTC, joinemm commented on utils.groovy
> +  archive_artifacts("ghaf-parallel-hw-test")
We can't archive the whole directory while there might be other hardware tests in the middle of creating files there. Use the new target argument to only archive the subdirectory of the current target:

```
archive_artifacts("ghaf-parallel-hw-test", flakeref_trimmed)

2024-10-11 07:46 UTC, joinemm requested changes

2024-10-11 07:46 UTC, joinemm commented on ghaf-parallel-pipeline.groovy
> +                  def scsdir = "scs/${target}/scs"
timestamps and scs variables are not used

2024-10-11 10:29 UTC, joinemm approved these changes

2024-10-11 10:59 UTC, merged