Add flash script for each target artifacts
tiiuae/ghaf-jenkins-pipeline pull request #81
Opened 2024-10-30 13:15 UTC by mnokka-unikie

Adding flash script to each but docs target artifiact directory

2024-10-30 13:43 UTC, joinemm commented
Please fix inconsistent indentation and formatting

2024-10-31 06:54 UTC, henrirosten commented
This seems overly complicated to me.

If it's the same flash script for all of those targets, wouldn't it be far simpler if just copied the script to the root of the build artifacts, e.g. here: https://ghaf-jenkins-controller-prod.northeurope.cloudapp.azure.com/artifacts/ghaf-main-pipeline/build_12-commit_147f806264d2fb9d9026d4221b7cfbd69587bb61/, instead of placing it inside each target artifact directory?

2024-10-31 07:50 UTC, mnokka-unikie commented
Testers wanted to have copy in each target directory ("just one script copy approach was offered"). They "approved" the current solution, hence now we have development vs. user acceptance phenomena

2024-10-31 08:09 UTC, milva-unikie commented
Hello from the testing team (& also from the user trials point of view)

Having a separate script for each target makes it a lot more easier to use. In the testing side we for sure could deal with that, but we also have now user trial participants that are using Artifacts. Many of them don't know what the different targets are or how Jenkins folders work. When the script is in the same folder as the image, we can just send one link and everything needed will be there.

2024-10-31 12:13 UTC, mkaapu commented
If flashing scripts are something, we should also provide to end users, then they should also be part of target build output.
In this case with current implementation, we would need no changes to Pipeline scripts as they were simply archived with the rest of the build result files.

2024-12-10 09:20 UTC, henrirosten requested changes
Proposing to close this with the alternative resolution @mkaapu referenced above

2025-01-08 14:46 UTC, closed without merging