Add slack message for possible HW tests failure
tiiuae/ghaf-jenkins-pipeline pull request #97
Opened 2024-11-21 09:37 UTC by mnokka-unikie

2024-11-21 11:42 UTC, cazfi requested changes

2024-11-21 11:42 UTC, cazfi commented on ghaf-main-pipeline.groovy
> +  ],https://github.com/tiiuae/ghaf-jenkins-pipeline.git
Accidental addition?

2024-11-21 12:11 UTC, mnokka-unikie commented on ghaf-main-pipeline.groovy
> +  ],https://github.com/tiiuae/ghaf-jenkins-pipeline.git
I need new keyboard...

2024-11-22 06:41 UTC, mnokka-unikie commented on ghaf-main-pipeline.groovy
> +  ],https://github.com/tiiuae/ghaf-jenkins-pipeline.git
change force changed (one commit only policy)

2024-11-22 10:53 UTC, cazfi approved these changes

2024-11-22 13:08 UTC, merged